version: '3'
services:
  frontend:
    container_name: 'cgu-ot-fe'
    image: music1353/cgu-ot-fe:2.0.1
    restart: always
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Taipei
    depends_on:
      - backend
  backend:
    container_name: 'cgu-ot-be'
    image: music1353/cgu-ot-be:2.0.2
    restart: always
    ports:
      - "5000:5000"
    environment:
      - TZ=Asia/Taipei
    volumes:
      - backup-volume:/usr/src/app/backup
    depends_on:
      - db
  db:
    container_name: 'mongo'
    image: mongo
    environment:
      - TZ=Asia/Taipei
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
volumes:
    data-volume:
    backup-volume: